# NUMPY

El almacenamiento y la manipulación eficientes de matrices numéricas es absolutamente fundamental para el proceso de hacer ciencia de datos.

La ciencia y la computación basadas en datos eficaces requieren comprender cómo se almacenan y manipulan los datos. Esta sección describe y contrasta cómo se manejan las matrices de datos en el propio lenguaje Python y cómo NumPy mejora esto.

Podemos crear una <a style="color:red;"> <b> lista de números enteros </b> </a> de la siguiente manera:

In [1]:
L = list(range(5))
L

[0, 1, 2, 3, 4]

In [2]:
type(L[0])

int

O, de manera similar, una <a style="color:red;"> <b> lista de cadenas. </b> </a>:

In [3]:
L2 = [str(c) for c in L]
L2

['0', '1', '2', '3', '4']

In [4]:
type(L2[0])

str

Gracias a la tipificación dinámica de Python, podemos incluso crear <a style="color:red;"> <b> listas heterogéneas: </b> </a>

In [5]:
L3 = [True, "2", 3.0, 4]
[type(item) for item in L3]

[bool, str, float, int]

# <a style="color:blue;"> <b> Crear matrices a partir de listas de Python </b> </a>

In [9]:
import numpy as np
# integer array:
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

podemos usar <a style="color:red;"> <b> np.array </b> </a> para crear matrices a partir de listas de Python. <a style="color:black;"> <b> NumPy está restringido a matrices que contienen todas el mismo tipo. </b> </a>.Si los tipos no coinciden, NumPy realizará una conversión ascendente si es posible

In [10]:
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

Si queremos establecer explícitamente el tipo de datos de la matriz resultante, podemos usar la palabra clave <a style="color:red;"> <b> dtype </b> </a>

In [11]:
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

<a style="color:black;"> <b> <a style="color:black;"> <b> NumPy está restringido a matrices que contienen todas el mismo tipo. </b> </a> </b> </a> Aquí hay una forma de inicializar una matriz multidimensional usando una lista de listas:

In [13]:
np.array([range(i, i + 5) for i in [2, 3, 4, 6]])

array([[ 2,  3,  4,  5,  6],
       [ 3,  4,  5,  6,  7],
       [ 4,  5,  6,  7,  8],
       [ 6,  7,  8,  9, 10]])

Las listas internas se tratan como filas de la matriz bidimensional resultante.

# <a style="color:blue;"> <b> Creando matrices desde cero </b> </a>

Especialmente para matrices más grandes, es más eficiente crear matrices desde cero utilizando rutinas integradas en NumPy. A continuación se muestran varios ejemplos:

In [15]:
np.zeros(5, dtype=int) #Crea una matriz de enteros de longitud 5 llena de ceros

array([0, 0, 0, 0, 0])

In [17]:
np.ones((2, 3), dtype=float) #Crea una matriz de punto flotante de 2x3 llena de unos

array([[1., 1., 1.],
       [1., 1., 1.]])

In [19]:
np.full((4, 4), 3.141621) #Crea una matriz de 4x4 llena de 3.141621

array([[3.141621, 3.141621, 3.141621, 3.141621],
       [3.141621, 3.141621, 3.141621, 3.141621],
       [3.141621, 3.141621, 3.141621, 3.141621],
       [3.141621, 3.141621, 3.141621, 3.141621]])

In [21]:
np.arange(0, 20, 3) # Crea una matriz llena con una secuencia lineal Comenzando en 0, terminando en 20, avanzando en 3

array([ 0,  3,  6,  9, 12, 15, 18])

In [27]:
np.linspace(1, 2, 5) #Crea una matriz de cinco valores espaciados uniformemente entre 1 y 2

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [29]:
np.random.random((3, 3)) #Cree una matriz de 3x3 distribuida uniformemente. Valores aleatorios entre 0 y 1

array([[0.87101548, 0.54317693, 0.80432988],
       [0.58836172, 0.90803073, 0.32336906],
       [0.63174786, 0.73365409, 0.30928282]])

In [31]:
np.random.normal(0, 1, (3, 3)) #Cree una matriz de 3x3 de valores aleatorios distribuidos normalmente. 
#con media 0 y desviación estándar 1

array([[ 1.29692445, -1.28410933,  0.78533342],
       [-0.33856446,  0.91093053, -0.11118452],
       [ 0.3374602 ,  0.39556124, -0.1317652 ]])

In [33]:
np.random.randint(0, 10, (3, 3)) #Crea una matriz de 3x3 de enteros aleatorios en el intervalo [0, 10)

array([[5, 6, 5],
       [4, 5, 1],
       [1, 6, 1]])

In [36]:
np.eye(5) #Crea una matriz de identidad de 5x5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

Tenga en cuenta que al construir una matriz, puede especificarlos usando una cadena

In [37]:
np.eye(5, dtype='int16')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]], dtype=int16)

# <a style="color:blue;"> <b> Los conceptos básicos de las matrices NumPy </b> </a>

Cubriremos algunas categorías de manipulaciones básicas de matrices aquí:

* <a style="color:black;"> <b> Atributos de las matrices:</b> </a>  Determinar el tamaño, la forma, el consumo de memoria y los tipos de datos de las matrices.

* <a style="color:black;"> <b> Indexación de matrices:</b> </a> Obtener y establecer el valor de elementos de matriz individuales

* <a style="color:black;"> <b> Rebanado de matrices:</b> </a> Obtener y configurar subarreglos más pequeños dentro de un arreglo más grande

* <a style="color:black;"> <b> Remodelación de matrices: </b> </a>  Cambiar la forma de una matriz determinada

* <a style="color:black;"> <b> Unión y división de matrices: </b> </a>  Combinar varias matrices en una y dividir una matriz en muchas

# <a style="color:red;"> <b>Atributos de las matrices: </b> </a>

Usaremos el generador de números aleatorios de NumPy, que sembraremos con un valor establecido para garantizar que se generen las mismas matrices aleatorias cada vez que se ejecute este código:

In [49]:
import numpy as np
np.random.seed(0)  # seed for reproducibility
x1 = np.random.randint(10, size=6)  # One-dimensional array
print("Matriz unidimensional\n ")
print(x1)
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
print("\n Matriz bidimensional\n ")
print(x2)
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array
print("\n Matriz tridimensional \n")
print(x3)

Matriz unidimensional
 
[5 0 3 3 7 9]

 Matriz bidimensional
 
[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]

 Matriz tridimensional 

[[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]]


Cada matriz tiene atributos  <a style="color:red;"> <b> ndim </b> </a> (el número de dimensiones), <a style="color:red;"> <b> shape </b> </a>(el tamaño de cada dimensión) y <a style="color:red;"> <b> size </b> </a> (el tamaño total de la matriz):

In [53]:
print("x1 ndim: ", x1.ndim)
print("x1 shape:", x1.shape)
print("x1 size: ", x1.size)

x1 ndim:  1
x1 shape: (6,)
x1 size:  6


In [52]:
print("x2 ndim: ", x2.ndim)
print("x2 shape:", x2.shape)
print("x2 size: ", x2.size)

x2 ndim:  2
x2 shape: (3, 4)
x2 size:  12


In [51]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


Otro atributo útil es el <a style="color:red;"> <b> dtype </b> </a> tipo de datos de la matriz

In [54]:
print("dtype:", x3.dtype)

dtype: int32


# <a style="color:red;"> <b> Indexación de matrices: acceso a elementos individuales: </b> </a> 
En una <a style="color:black;"> <b> matriz unidimensional </b> </a>, puede acceder al <a style="color:black;"> <b> i -ésimo </b> </a> valor (contando desde cero) especificando el índice deseado entre corchetes, tal como con las listas de Python:

In [55]:
x1

array([5, 0, 3, 3, 7, 9])

In [56]:
x1[0]

5

In [59]:
x1[2]

3

Para indexar desde el final de la matriz, puede utilizar índices negativos:

In [60]:
x1[-1]

9

In [61]:
x1[-2]

7

En una <a style="color:black;"> <b> matriz multidimensional </b> </a>, se accede a los elementos mediante una tupla de índices separados por comas :

In [62]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [68]:
x2[0, 0]

3

In [69]:
x2[0, 1]

5

In [71]:
x2[0, -1]

4

También puede modificar valores utilizando cualquiera de las notaciones de índice anteriores:

In [73]:
x2[2, -1] = 15
x2

array([[ 3,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7, 15]])

Tenga en cuenta que, a diferencia de las listas de Python, las <a style="color:black;"> <b> matrices NumPy tienen un tipo fijo. </b> </a> Esto significa, por ejemplo, que si intenta insertar un valor de punto flotante en una matriz de enteros, el valor se truncará silenciosamente. ¡No se deje sorprender por este comportamiento!

In [74]:
x1

array([5, 0, 3, 3, 7, 9])

In [75]:
x1[0]

5

In [77]:
x1[0]=3.14161 #¡Esto será truncado!, ya que esta en una matriz de enteros
x1

array([3, 0, 3, 3, 7, 9])

# <a style="color:red;"> <b> División de matrices: acceso a submatrices </b> </a> 

Justo como podemos usar corchetes para acceder a elementos de matriz individuales, también podemos usarlos para acceder a submatrices con la notación de corte , marcada por elcarácter de dos puntos <a style="color:black;"> <b> (:) </b> </a>.

x[start:stop:step]

Si alguno de estos no está especificado, su valor predeterminado es start=0, , . 

In [78]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [80]:
x[:6] #primeros 6 elementos

array([0, 1, 2, 3, 4, 5])

In [83]:
x[3:] #elementos después del índice 3

array([3, 4, 5, 6, 7, 8, 9])

In [84]:
x[4:8] #elementos después del índice 4 y antes del índice 8

array([4, 5, 6, 7])

In [85]:
x[::3] #Cada 3er elemento empezando desde 0

array([0, 3, 6, 9])

In [86]:
x[1::2] #CDada 2do elemento empezando desde 1

array([1, 3, 5, 7, 9])

Un caso potencialmente confuso es cuando el valor <a style="color:black;"> <b>  step es negativo. </b> </a> En este caso, se intercambian los valores predeterminados de start y stop. Esta se convierte en una forma conveniente de invertir una matriz:

In [87]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [89]:
x[5::-2]

array([5, 3, 1])